### ISSUE TITLE
Failed to load DynamiteLoader

### ISSUE THREAD

**Issue by bentomas** [mapsplugin/v2.0-demo#20]
When I try and run the app on my Galaxy S5, this is what I get:

> E/DynamiteModule(23888): Failed to load DynamiteLoader: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader" on path: DexPathList[[zip file "/data/app/cordova.google.maps-1.apk"],nativeLibraryDirectories=[/data/app-lib/cordova.google.maps-1, /vendor/lib, /system/lib]]

I'm also getting this when I'm running my own custom app running the latest version 1.4.0-beta.

Am I missing a dependency?  I'm having trouble figuring this out.

**Comment by wf9a5m75** [comment]
It seems your build system does not build your app with the Google Play Services library.

**Comment by canadaka** [comment]
My map loads but I see this same error in LogCat. My cordova android platform folder definitely has GMS loaded.

![image](https://cloud.githubusercontent.com/assets/108178/20507175/009cdb0e-b00e-11e6-8ac3-695ef3f32244.png)

**Comment by wf9a5m75** [comment]
Regarding of the stack overflow, it seems the bug of the Google Play Services.
http://stackoverflow.com/questions/40701107/why-i-get-this-error-when-on-google-map-failed-to-load-dynamiteloader-java-lan#comment68632857_40701557

For this plugin, try to change the version number of these lines in your local:
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/06f02e8bf833cab22839fa6dd41fb021437a8d5e/plugin.xml#L145-L146

`com.google.android.gms:play-services-maps:9.0.0` instead of `com.google.android.gms:play-services-maps:9.8.0`

or

`com.google.android.gms:play-services-maps:10.0.0` instead of `com.google.android.gms:play-services-maps:9.8.0`

-----

```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps
$> cd cordova-plugin-googlemaps
$> git checkout multiple_maps
$> vim plugin.xml   <--- Edit the version numbers
$> cd ..
$> cd (your project)
$> cordova plugin add (path to the plugin dir)/cordova-plugin-googlemaps --variable API_KEY...
```

**Comment by canadaka** [comment]
thanks! I updated the plugin to use Google Play Services  v10.0.0 and the error is gone.

**Comment by wf9a5m75** [comment]
Thanks for your update. I updated the plugin.xml
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/457f5ee1cfde575f7e360aa27d1bedaa5761d066/plugin.xml#L145-L146
